server:
  port: 8300

spring:
  profiles:
    active: dev
  application:
    name: blog-handle

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true         #是否启用 health端点
      show-details: ALWAYS  #显示完整的健康详情

debug: true
