spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/blogp?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
  session:
    store-type: none





mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.jackie.blogasd.mapper