server:
  port: 8200

spring:
  profiles:
    active: dev
  application:
    name: blog-asd

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true         #是否启用 health端点
      show-details: ALWAYS  #显示完整的健康详情

debug: true

##logging
logging:
  level:
    com:
      jackie:
        blogasd:
          mapper: debug