#spring
spring:
#  redis:
##    host: 80.2.21.68
##    port: 6379
##    password:
##    database: 1
#    password:
#      database: 0
#      lettuce:
#        pool:
#          max-active: 8
#          max-idle: 300
#          min-idle: 20
#          max-wait: -1
#      timeout: 15000
#      commandTimeout: 5000
#    cluster:
#      nodes: 80.2.21.71:7101,80.2.21.71:7102,80.2.21.72:7201,80.2.21.72:7202,80.2.21.73:7301,80.2.21.73:7302
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.120:3306/blogmyapp?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    filters: stat,wall
    maxActive: 10
    initialSize: 5
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
    session:
      store-type: none



#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.jackie.myapp.mapper
