#端口设置
server:
  port: 8150

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogp?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    session:
      store-type: none
