spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blogp?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
  session:
    store-type: none
