spring:
  application:
    name: blog-web

    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.120:3306/blogp?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: admin
    session:
      store-type: none


  thymeleaf:
    prefix: classpath:/static/



mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.jackie.blogweb.mapper