server:
  port: 8100

spring:
  profiles:
    active: dev
  application:
    name: blog-asd



  thymeleaf:
    prefix: classpath:/static/
    cache: true

  resources:
    static-locations: classpath:/static/




debug: true
