server:
  port: 8080
spring:
  application:
    name: blog-web
  thymeleaf:
    prefix: classpath:/static/
#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.1.200:11111/eureka/
